### PR TITLE
Allow private screenshots on S3

### PR DESCRIPTION
**Pull request by EmanueleMinotto**
Screenshots can't be uploaded as private because the driver forces the visibility to `public-read` and doesn't give the temporary & signed URL.

Could this be a `0.1.4` version? Thanks

### CODE REVIEW

**Comment by EmanueleMinotto** [comment]
@artursvonda only HHVM is failed, but it's no more supported by the Symfony dependencies.
What about replacing it with PHP 7.2 instead?

**Comment by artursvonda** [comment]
Merged. Thanks, @EmanueleMinotto!

**Comment by artursvonda** [comment]
Released as 0.1.4 (https://github.com/lingoda/behat-screenshot-image-driver-aws-s3/releases/tag/0.1.4)

**Comment by EmanueleMinotto** [comment]
Thank you @artursvonda 
I'm afraid the packagist webhook wasn't triggered, can you please check it too?

**Comment by artursvonda** [comment]
Should be there now

**Comment by EmanueleMinotto** [comment]
Perfect! Thanks again 😃

**Pull request merged**
